name: Run test cases

on: [push, pull_request]

jobs:    
    run_test_cases:
        runs-on: ubuntu-latest
      
        container:
            image: erlang:22.1
            
        steps:
            - uses: actions/checkout@v1
            - name: get reflog
              run: |
                env
                git tag -l "v*" --points-at  $( git show $(git describe --tags |  grep -oE "[ev0-9]+\.[0-9]+(\.[0-9]+)?(-alpha|-beta|-rc)?\.[0-9]") --notes |grep commit |awk '{print $2}' )
                git show $GITHUB_SHA
                git reflog show
            - name: run test cases
              run: |
                make xref
                make eunit
                make ct
                make cover
            - uses: actions/upload-artifact@v1
              if: always()
              with:
                name: logs
                path: _build/test/logs
            - uses: actions/upload-artifact@v1
              with:
                name: cover
                path: _build/test/cover

